// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fjevzbahkakjnukpvrxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZqZXZ6YmFoa2Fram51a3B2cnhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MzM4MzQsImV4cCI6MjA1OTIwOTgzNH0.mjEyGiJIdifGOQrNhDou1vgzSNkKDjF9pSLon9i2g_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);